name: shopster
description: "Shopster app"
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flex_color_scheme: ^8.0.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  font_awesome_flutter: ^10.8.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.20.1
  logger: ^2.5.0
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/logos/
    - assets/images/on_boarding/
